module(
    name = "bzlmodrio-opencv",
    version = "2027.4.13.0-3",
    compatibility_level = 2027,
)

bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.13")
bazel_dep(name = "rules_java", version = "8.16.1")
bazel_dep(name = "rules_bzlmodrio_toolchains", version = "2025-1.bcr7")

setup_bzlmodrio_opencv_cpp_dependencies = use_extension("//:maven_cpp_deps.bzl", "setup_bzlmodrio_opencv_cpp_dependencies")
use_repo(
    setup_bzlmodrio_opencv_cpp_dependencies,
    "org_wpilib_opencv-cpp_headers",
    "org_wpilib_opencv-cpp_linuxarm64",
    "org_wpilib_opencv-cpp_linuxarm64debug",
    "org_wpilib_opencv-cpp_linuxarm64static",
    "org_wpilib_opencv-cpp_linuxarm64staticdebug",
    "org_wpilib_opencv-cpp_linuxsystemcore",
    "org_wpilib_opencv-cpp_linuxsystemcoredebug",
    "org_wpilib_opencv-cpp_linuxsystemcorestatic",
    "org_wpilib_opencv-cpp_linuxsystemcorestaticdebug",
    "org_wpilib_opencv-cpp_linuxx86-64",
    "org_wpilib_opencv-cpp_linuxx86-64debug",
    "org_wpilib_opencv-cpp_linuxx86-64static",
    "org_wpilib_opencv-cpp_linuxx86-64staticdebug",
    "org_wpilib_opencv-cpp_osxarm64",
    "org_wpilib_opencv-cpp_osxarm64debug",
    "org_wpilib_opencv-cpp_osxarm64static",
    "org_wpilib_opencv-cpp_osxarm64staticdebug",
    "org_wpilib_opencv-cpp_osxuniversal",
    "org_wpilib_opencv-cpp_osxuniversaldebug",
    "org_wpilib_opencv-cpp_osxuniversalstatic",
    "org_wpilib_opencv-cpp_osxuniversalstaticdebug",
    "org_wpilib_opencv-cpp_osxx86-64",
    "org_wpilib_opencv-cpp_osxx86-64debug",
    "org_wpilib_opencv-cpp_osxx86-64static",
    "org_wpilib_opencv-cpp_osxx86-64staticdebug",
    "org_wpilib_opencv-cpp_sources",
    "org_wpilib_opencv-cpp_windowsarm64",
    "org_wpilib_opencv-cpp_windowsarm64debug",
    "org_wpilib_opencv-cpp_windowsarm64static",
    "org_wpilib_opencv-cpp_windowsarm64staticdebug",
    "org_wpilib_opencv-cpp_windowsx86-64",
    "org_wpilib_opencv-cpp_windowsx86-64debug",
    "org_wpilib_opencv-cpp_windowsx86-64static",
    "org_wpilib_opencv-cpp_windowsx86-64staticdebug",
)

bazel_dep(name = "rules_jvm_external", version = "6.8")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "org.wpilib.thirdparty.opencv:opencv-java:2027-4.13.0-3",
    ],
    fetch_sources = True,
    known_contributing_modules = [
        "bzlmodrio-opencv",
        "protobuf",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
        "https://frcmaven.wpi.edu/artifactory/release/",
    ],
)
use_repo(maven, "maven")
